#!/bin/bash

set -ex

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build project for release.
"
}

if [ "${BASH_SOURCE}[0]}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else

    ./scripts/setup "$1"

    fi
fi
